#!/bin/sh

# include custom /etc/firewall.user rules
uci set firewall.firewall_user=include
uci set firewall.firewall_user.path='/etc/firewall.user'
uci commit firewall

modprobe xt_FULLCONENAT

# add firewall rule to make fullcone NAT
cat >>/etc/firewall.user <<EOF
iptables -t nat -I zone_wan_prerouting -j FULLCONENAT
iptables -t nat -I zone_wan_postrouting -j FULLCONENAT
EOF

# make /etc/firewall.user survive firewall reload
uci set firewall.@include[0].reload=1
uci commit firewall
/etc/init.d/firewall reload

exit 0
