name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set the value
      run: |
        echo "FIRMWARE_SLUG=$(echo $GITHUB_REF | cut -d/ -f3)" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: apt update
      run: sudo apt update
    - name: apt install
      run: sudo apt install -y liblzo2-dev mtd-utils squashfs-tools fakeroot
    - name: pip upgrade
      run: python -m pip install --upgrade pip
    - name: pip install
      run: pip install python-lzo ubi_reader
    - name: make
      run: make
      
    - uses: actions/upload-artifact@v3
      with:
        name: miwifi_ra72_firmware_98605_1.0.55+SSH
        path: miwifi_ra72_firmware_98605_1.0.55+SSH.bin


